# $Id: Makefile,v 1.4 2000-02-07 00:59:20 arensb Exp $

# XXX - This Makefile is temporary. It should be replaced by a Makefile.PL

TOP =		.
SUBDIR =	perl

SUBDIRS =	ColdSync

DISTFILES =	Makefile ColdSync.pm

CLEAN =		*.bak *~ core *.core

include ${TOP}/Make.rules
