# $Id: Makefile,v 1.5 2000-02-07 19:16:03 arensb Exp $

# XXX - This Makefile is temporary. It should be replaced by a Makefile.PL

TOP =		.
SUBDIR =	perl

SUBDIRS =	ColdSync

DISTFILES =	Makefile

CLEAN =		*.bak *~ core *.core

include ${TOP}/Make.rules
