.\" DlpReadOpenDBInfo.3
.\" 
.\" Copyright 2001, Andrew Arensburger.
.\" You may distribute this file under the terms of the Artistic
.\" License, as specified in the README file.
.\"
.\" $Id: DlpReadOpenDBInfo.3,v 1.1 2001-09-05 07:29:21 arensb Exp $
.\"
.\" This man page uses the 'mdoc' formatting macros. If your 'man' uses
.\" the old 'man' package, you may run into problems.
.\"
.Dd Aug 16, 2001
.Dt DlpReadOpenDBInfo 3
.Sh NAME
.Nm DlpReadOpenDBInfo
.Nd read information about a PalmOS database
.Sh LIBRARY
.Pa libpconn
.Sh SYNOPSIS
.Fd #include <palm.h>
.Fd #include <pconn/pconn.h>
.Ft int
.Fn DlpReadOpenDBInfo "PConnection *pconn" "ubyte handle" "struct dlp_opendbinfo *dbinfo"
.Sh DESCRIPTION
.Nm
reads information about a database on the Palm.
.Pp
.Fa handle
is the database handle given by
.Nm DlpOpenDB .
.Pp
.Fa dbinfo
is filled in with information about the database. The
.Ft dlp_opendbinfo
structure is trivial:
.Bd -literal -offset indent
struct dlp_opendbinfo
{
	uword numrecs;
};
.Ed
where
.Fa numrecs
is the number of records or resources in the database.
.Sh RETURN VALUE
.Nm
returns 0 if successful, or a negative value otherwise.
.Sh NOTES
The fact that this function takes an entire structure for a single
value may be considered a bug. However, with a name like
.Dq read open DB info,
it seems likely that in future versions, this function might return
far more information.
.Sh SEE ALSO
.Xr libpconn 3 ,
.Xr DlpOpenDB 3 .
