.\" DlpResetSyncFlags.3
.\" 
.\" Copyright 2001, Andrew Arensburger.
.\" You may distribute this file under the terms of the Artistic
.\" License, as specified in the README file.
.\"
.\" $Id: DlpResetSyncFlags.3,v 1.1 2001-09-05 07:29:33 arensb Exp $
.\"
.\" This man page uses the 'mdoc' formatting macros. If your 'man' uses
.\" the old 'man' package, you may run into problems.
.\"
.Dd Aug 16, 2001
.Dt DlpResetSyncFlags 3
.Sh NAME
.Nm DlpResetSyncFlags
.Nd clear sync flags on a PalmOS database
.Sh LIBRARY
.Pa libpconn
.Sh SYNOPSIS
.Fd #include <palm.h>
.Fd #include <pconn/pconn.h>
.Ft int
.Fn DlpResetSyncFlags "PConnection *pconn" "const ubyte handle"
.Sh DESCRIPTION
For record databases,
.Nm
clears the dirty flag on each record; for both record and resource
databases, sets the
.Dq last sync
time to now.
.Pp
.Fa handle
is the database handle, as returned by
.Xr DlpOpenDB 3 .
.Sh RETURN VALUE
.Nm
returns 0 if successful, or a negative value otherwise.
.Sh SEE ALSO
.Xr libpconn 3 ,
.Xr DlpOpenDB 3 .
