TOP =		../..
SUBDIR =	include/pconn

DISTFILES =	Makefile \
		PConnection.h \
		cmp.h \
		dlp.h \
		dlp_cmd.h \
		padp.h \
		palm_errno.h \
		palm_types.h \
		pconn.h \
		slp.h \
		util.h

all::

include ${TOP}/Make.rules
