#!/usr/bin/perl -w

use strict;

use ColdSync;
use ColdSync::SPC qw( :DEFAULT :dlp_args );
use ColdSync::SPC::ExpSlot;

use Data::Dumper;


StartConduit('sync');


	print "Enumerating ExpSlot(s)...\n";
	my $ek = dlp_ExpSlotEnumerate();
	print "\n";

	print Data::Dumper->Dump( [ $ek ] );

	print "\nDumping slot(s) info..\n";

	my $err;

	foreach my $slot ( @{$ek->{'slots'}} )
	{
		my $exp = dlp_ExpSlotMediaType($slot);

		print "\nSlot $slot: " . Data::Dumper->Dump( [ $exp ] );

		$err = dlp_ExpCardPresent($slot);

		if ($err eq dlpRespErrNone)
		{
			$exp = dlp_ExpCardInfo($slot);
			print "\n\tCard: " . Data::Dumper->Dump( [ $exp ] );
		}
		else
		{
			print "\n\tCard not present\n";
		}
	}

	print "\n";


EndConduit();
