# $Id: Makefile,v 1.3 2000-02-03 03:24:29 arensb Exp $

# XXX - This Makefile is temporary. It should be replaced by a Makefile.PL

TOP =		.
SUBDIR =	perl

DISTFILES =	Makefile ColdSync.pm

CLEAN =		*.bak *~ core *.core

include ${TOP}/Make.rules
