# $Id: Makefile,v 1.2 2000-02-03 02:53:01 arensb Exp $

TOP =		../..
SUBDIR =	include/pconn

HEADERS =	PConnection.h \
		cmp.h \
		dlp.h \
		dlp_cmd.h \
		padp.h \
		palm_errno.h \
		palm_types.h \
		pconn.h \
		slp.h \
		util.h

DISTFILES =	Makefile \
		${HEADERS}

all::

include ${TOP}/Make.rules
